### ISSUE TITLE
训练中遇到的问题

### ISSUE THREAD

**Issue by littleblackzi** [opendilab/InterFuser#104]
作者你好，我在学习了 [#8 ](url)之后，将源代码修改为适用于单gpu训练的代码，但是我遇到了以下问题
/home/oem/anaconda3/envs/interfuser/lib/python3.7/site-packages/torch/distributed/launch.py:188: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  FutureWarning,
Training with a single process on 1 GPUs.
Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-weights/resnet50d_ra2-464e36ba.pth)
Model interfuser_baseline created, param count:52935567
Data processing configuration for current model + dataset:
        input_size: (3, 224, 224)
        interpolation: bicubic
        mean: (0.485, 0.456, 0.406)
        std: (0.229, 0.224, 0.225)
        crop_pct: 0.875
CNN backbone and transformer blocks using different learning rates!
165 weights in the cnn backbone, 274 weights in other modules
AMP not enabled. Training in float32.
Scheduled epochs: 35
Sub route dir nums: 7329
Sub route dir nums: 332
Train: 0 [   0/458 (  0%)]  Loss(traffic):  0.339803 (0.3398)  Loss(waypoints):  1.734139 (1.7341)  Loss(junction):  0.719862 (0.7199)  Loss(light):  0.637060 (0.6371)  Loss:  0.645103 (0.6451)  Time: 5.235s,    3.06/s  (5.235s,    3.06/s)  LR: 5.000e-06  Data: 2.718 (2.718)
Train: 0 [  50/458 ( 11%)]  Loss(traffic):  0.323523 (0.3254)  Loss(waypoints):  0.503998 (0.8651)  Loss(junction):  0.754921 (0.7374)  Loss(light):  0.297636 (0.4673)  Loss:  0.355306 (0.4452)  Time: 0.198s,   80.86/s  (0.328s,   48.76/s)  LR: 5.000e-06  Data: 0.000 (0.057)
Train: 0 [ 100/458 ( 22%)]  Loss(traffic):  0.307639 (0.3189)  Loss(waypoints):  0.333984 (0.6701)  Loss(junction):  0.569275 (0.6814)  Loss(light):  0.657482 (0.5307)  Loss:  0.332782 (0.4001)  Time: 0.201s,   79.58/s  (0.277s,   57.69/s)  LR: 5.000e-06  Data: 0.001 (0.030)
Train: 0 [ 150/458 ( 33%)]  Loss(traffic):  0.314110 (0.3138)  Loss(waypoints):  0.279552 (0.5642)  Loss(junction):  0.666111 (0.6775)  Loss(light):  0.209753 (0.4505)  Loss:  0.288590 (0.3738)  Time: 0.248s,   64.47/s  (0.260s,   61.64/s)  LR: 5.000e-06  Data: 0.003 (0.021)
Train: 0 [ 200/458 ( 44%)]  Loss(traffic):  0.283651 (0.3094)  Loss(waypoints):  0.158541 (0.4985)  Loss(junction):  0.651932 (0.6724)  Loss(light):  0.438185 (0.4480)  Loss:  0.268704 (0.3569)  Time: 0.206s,   77.81/s  (0.251s,   63.82/s)  LR: 5.000e-06  Data: 0.000 (0.017)
Train: 0 [ 250/458 ( 55%)]  Loss(traffic):  0.293980 (0.3056)  Loss(waypoints):  0.302251 (0.4577)  Loss(junction):  0.618065 (0.6634)  Loss(light):  0.546156 (0.4644)  Loss:  0.309321 (0.3453)  Time: 0.199s,   80.26/s  (0.246s,   65.12/s)  LR: 5.000e-06  Data: 0.003 (0.014)
Train: 0 [ 300/458 ( 66%)]  Loss(traffic):  0.282016 (0.3024)  Loss(waypoints):  0.284371 (0.4219)  Loss(junction):  0.528329 (0.6441)  Loss(light):  0.377796 (0.4520)  Loss:  0.279544 (0.3357)  Time: 0.222s,   72.14/s  (0.242s,   66.05/s)  LR: 5.000e-06  Data: 0.000 (0.012)
Train: 0 [ 350/458 ( 77%)]  Loss(traffic):  0.271887 (0.2996)  Loss(waypoints):  0.282910 (0.3946)  Loss(junction):  0.364477 (0.6091)  Loss(light):  0.373431 (0.4422)  Loss:  0.262630 (0.3258)  Time: 0.220s,   72.89/s  (0.240s,   66.65/s)  LR: 5.000e-06  Data: 0.004 (0.011)
Train: 0 [ 400/458 ( 88%)]  Loss(traffic):  0.289339 (0.2972)  Loss(waypoints):  0.264469 (0.3696)  Loss(junction):  0.576778 (0.6055)  Loss(light):  0.583759 (0.4579)  Loss:  0.302020 (0.3172)  Time: 0.239s,   67.03/s  (0.238s,   67.09/s)  LR: 5.000e-06  Data: 0.000 (0.010)
Train: 0 [ 450/458 ( 98%)]  Loss(traffic):  0.279504 (0.2949)  Loss(waypoints):  0.187622 (0.3488)  Loss(junction):  0.249292 (0.5699)  Loss(light):  0.213236 (0.4334)  Loss:  0.227818 (0.3089)  Time: 0.193s,   82.90/s  (0.236s,   67.92/s)  LR: 5.000e-06  Data: 0.002 (0.009)
Train: 0 [ 457/458 (100%)]  Loss(traffic):  0.273590 (0.2946)  Loss(waypoints):  0.113988 (0.3452)  Loss(junction):  0.293756 (0.5448)  Loss(light):  0.351602 (0.4260)  Loss:  0.226542 (0.3076)  Time: 0.203s,   79.00/s  (0.235s,   68.08/s)  LR: 5.000e-06  Data: 0.000 (0.009)
Test: [   0/20]  Time: 1.797 (1.797)  Loss:  0.2420 (0.2420)  Loss(traffic):  0.2934 (0.2934)  Loss(waypoints):  0.0998 (0.0998)  Loss(junction):  0.615165 (0.6152)  Loss(light):  0.332752 (0.3328)  Acc(junction): 62.500000 (62.5000)  Acc(light): 100.000000 (100.0000)  
Test: [  20/20]  Time: 0.705 (0.180)  Loss:  0.2608 (0.2662)  Loss(traffic):  0.2853 (0.2958)  Loss(waypoints):  0.1121 (0.0943)  Loss(junction):  0.930065 (0.5654)  Loss(light):  0.406960 (0.5764)  Acc(junction): 33.333336 (68.6747)  Acc(light): 83.333336 (65.9639)  
Traceback (most recent call last):
  File "train.py", line 1831, in <module>
    main()
  File "train.py", line 1290, in main
    epoch, metric=save_metric
  File "/media/oem/T7/InterFuser/interfuser/timm/utils/checkpoint_saver.py", line 86, in save_checkpoint
    os.link(last_save_path, save_path)
PermissionError: [Errno 1] Operation not permitted: './output/20241104-165051-interfuser_baseline-224-interfuser_baseline/last.pth.tar' -> './output/20241104-165051-interfuser_baseline-224-interfuser_baseline/checkpoint-0.pth.tar'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 132957) of binary: /home/oem/anaconda3/envs/interfuser/bin/python3
Traceback (most recent call last):
  File "/home/oem/anaconda3/envs/interfuser/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/oem/anaconda3/envs/interfuser/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/oem/anaconda3/envs/interfuser/lib/python3.7/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/home/oem/anaconda3/envs/interfuser/lib/python3.7/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/home/oem/anaconda3/envs/interfuser/lib/python3.7/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/home/oem/anaconda3/envs/interfuser/lib/python3.7/site-packages/torch/distributed/run.py", line 756, in run
    )(*cmd_args)
  File "/home/oem/anaconda3/envs/interfuser/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/oem/anaconda3/envs/interfuser/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 248, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-11-04_16:52:49
  host      : oem-System-Product-Name
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 132957)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
核心问题似乎出在这里：
PermissionError: [Errno 1] Operation not permitted: './output/20241104-165051-interfuser_baseline-224-interfuser_baseline/last.pth.tar' -> './output/20241104-165051-interfuser_baseline-224-interfuser_baseline/checkpoint-0.pth.tar'
请问有什么建议么？

**Comment by littleblackzi** [comment]
> 作者你好，我在学习了 [#8 ](url)之后，将源代码修改为适用于单gpu训练的代码，但是我遇到了以下问题 /home/oem/anaconda3/envs/interfuser/lib/python3.7/site-packages/torch/distributed/launch.py:188: FutureWarning: The module torch.distributed.launch is deprecated and will be removed in future. Use torchrun. Note that --use_env is set by default in torchrun. If your script expects `--local_rank` argument to be set, please change it to read from `os.environ['LOCAL_RANK']` instead. See https://pytorch.org/docs/stable/distributed.html#launch-utility for further instructions
> 
> # FutureWarning,
> Training with a single process on 1 GPUs.
> Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-weights/resnet50d_ra2-464e36ba.pth)
> Model interfuser_baseline created, param count:52935567
> Data processing configuration for current model + dataset:
> input_size: (3, 224, 224)
> interpolation: bicubic
> mean: (0.485, 0.456, 0.406)
> std: (0.229, 0.224, 0.225)
> crop_pct: 0.875
> CNN backbone and transformer blocks using different learning rates!
> 165 weights in the cnn backbone, 274 weights in other modules
> AMP not enabled. Training in float32.
> Scheduled epochs: 35
> Sub route dir nums: 7329
> Sub route dir nums: 332
> Train: 0 [ 0/458 ( 0%)] Loss(traffic): 0.339803 (0.3398) Loss(waypoints): 1.734139 (1.7341) Loss(junction): 0.719862 (0.7199) Loss(light): 0.637060 (0.6371) Loss: 0.645103 (0.6451) Time: 5.235s, 3.06/s (5.235s, 3.06/s) LR: 5.000e-06 Data: 2.718 (2.718)
> Train: 0 [ 50/458 ( 11%)] Loss(traffic): 0.323523 (0.3254) Loss(waypoints): 0.503998 (0.8651) Loss(junction): 0.754921 (0.7374) Loss(light): 0.297636 (0.4673) Loss: 0.355306 (0.4452) Time: 0.198s, 80.86/s (0.328s, 48.76/s) LR: 5.000e-06 Data: 0.000 (0.057)
> Train: 0 [ 100/458 ( 22%)] Loss(traffic): 0.307639 (0.3189) Loss(waypoints): 0.333984 (0.6701) Loss(junction): 0.569275 (0.6814) Loss(light): 0.657482 (0.5307) Loss: 0.332782 (0.4001) Time: 0.201s, 79.58/s (0.277s, 57.69/s) LR: 5.000e-06 Data: 0.001 (0.030)
> Train: 0 [ 150/458 ( 33%)] Loss(traffic): 0.314110 (0.3138) Loss(waypoints): 0.279552 (0.5642) Loss(junction): 0.666111 (0.6775) Loss(light): 0.209753 (0.4505) Loss: 0.288590 (0.3738) Time: 0.248s, 64.47/s (0.260s, 61.64/s) LR: 5.000e-06 Data: 0.003 (0.021)
> Train: 0 [ 200/458 ( 44%)] Loss(traffic): 0.283651 (0.3094) Loss(waypoints): 0.158541 (0.4985) Loss(junction): 0.651932 (0.6724) Loss(light): 0.438185 (0.4480) Loss: 0.268704 (0.3569) Time: 0.206s, 77.81/s (0.251s, 63.82/s) LR: 5.000e-06 Data: 0.000 (0.017)
> Train: 0 [ 250/458 ( 55%)] Loss(traffic): 0.293980 (0.3056) Loss(waypoints): 0.302251 (0.4577) Loss(junction): 0.618065 (0.6634) Loss(light): 0.546156 (0.4644) Loss: 0.309321 (0.3453) Time: 0.199s, 80.26/s (0.246s, 65.12/s) LR: 5.000e-06 Data: 0.003 (0.014)
> Train: 0 [ 300/458 ( 66%)] Loss(traffic): 0.282016 (0.3024) Loss(waypoints): 0.284371 (0.4219) Loss(junction): 0.528329 (0.6441) Loss(light): 0.377796 (0.4520) Loss: 0.279544 (0.3357) Time: 0.222s, 72.14/s (0.242s, 66.05/s) LR: 5.000e-06 Data: 0.000 (0.012)
> Train: 0 [ 350/458 ( 77%)] Loss(traffic): 0.271887 (0.2996) Loss(waypoints): 0.282910 (0.3946) Loss(junction): 0.364477 (0.6091) Loss(light): 0.373431 (0.4422) Loss: 0.262630 (0.3258) Time: 0.220s, 72.89/s (0.240s, 66.65/s) LR: 5.000e-06 Data: 0.004 (0.011)
> Train: 0 [ 400/458 ( 88%)] Loss(traffic): 0.289339 (0.2972) Loss(waypoints): 0.264469 (0.3696) Loss(junction): 0.576778 (0.6055) Loss(light): 0.583759 (0.4579) Loss: 0.302020 (0.3172) Time: 0.239s, 67.03/s (0.238s, 67.09/s) LR: 5.000e-06 Data: 0.000 (0.010)
> Train: 0 [ 450/458 ( 98%)] Loss(traffic): 0.279504 (0.2949) Loss(waypoints): 0.187622 (0.3488) Loss(junction): 0.249292 (0.5699) Loss(light): 0.213236 (0.4334) Loss: 0.227818 (0.3089) Time: 0.193s, 82.90/s (0.236s, 67.92/s) LR: 5.000e-06 Data: 0.002 (0.009)
> Train: 0 [ 457/458 (100%)] Loss(traffic): 0.273590 (0.2946) Loss(waypoints): 0.113988 (0.3452) Loss(junction): 0.293756 (0.5448) Loss(light): 0.351602 (0.4260) Loss: 0.226542 (0.3076) Time: 0.203s, 79.00/s (0.235s, 68.08/s) LR: 5.000e-06 Data: 0.000 (0.009)
> Test: [ 0/20] Time: 1.797 (1.797) Loss: 0.2420 (0.2420) Loss(traffic): 0.2934 (0.2934) Loss(waypoints): 0.0998 (0.0998) Loss(junction): 0.615165 (0.6152) Loss(light): 0.332752 (0.3328) Acc(junction): 62.500000 (62.5000) Acc(light): 100.000000 (100.0000)
> Test: [ 20/20] Time: 0.705 (0.180) Loss: 0.2608 (0.2662) Loss(traffic): 0.2853 (0.2958) Loss(waypoints): 0.1121 (0.0943) Loss(junction): 0.930065 (0.5654) Loss(light): 0.406960 (0.5764) Acc(junction): 33.333336 (68.6747) Acc(light): 83.333336 (65.9639)
> Traceback (most recent call last):
> File "train.py", line 1831, in
> main()
> File "train.py", line 1290, in main
> epoch, metric=save_metric
> File "/media/oem/T7/InterFuser/interfuser/timm/utils/checkpoint_saver.py", line 86, in save_checkpoint
> os.link(last_save_path, save_path)
> PermissionError: [Errno 1] Operation not permitted: './output/20241104-165051-interfuser_baseline-224-interfuser_baseline/last.pth.tar' -> './output/20241104-165051-interfuser_baseline-224-interfuser_baseline/checkpoint-0.pth.tar'
> ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 132957) of binary: /home/oem/anaconda3/envs/interfuser/bin/python3
> Traceback (most recent call last):
> File "/home/oem/anaconda3/envs/interfuser/lib/python3.7/runpy.py", line 193, in _run_module_as_main
> "**main**", mod_spec)
> File "/home/oem/anaconda3/envs/interfuser/lib/python3.7/runpy.py", line 85, in _run_code
> exec(code, run_globals)
> File "/home/oem/anaconda3/envs/interfuser/lib/python3.7/site-packages/torch/distributed/launch.py", line 195, in
> main()
> File "/home/oem/anaconda3/envs/interfuser/lib/python3.7/site-packages/torch/distributed/launch.py", line 191, in main
> launch(args)
> File "/home/oem/anaconda3/envs/interfuser/lib/python3.7/site-packages/torch/distributed/launch.py", line 176, in launch
> run(args)
> File "/home/oem/anaconda3/envs/interfuser/lib/python3.7/site-packages/torch/distributed/run.py", line 756, in run
> )(*cmd_args)
> File "/home/oem/anaconda3/envs/interfuser/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 132, in **call**
> return launch_agent(self._config, self._entrypoint, list(args))
> File "/home/oem/anaconda3/envs/interfuser/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 248, in launch_agent
> failures=result.failures,
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
> ## train.py FAILED
> ## Failures:
> <NO_OTHER_FAILURES>
> # Root Cause (first observed failure):
> [0]:
> time : 2024-11-04_16:52:49
> host : oem-System-Product-Name
> rank : 0 (local_rank: 0)
> exitcode : 1 (pid: 132957)
> error_file: <N/A>
> traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
> 核心问题似乎出在这里： PermissionError: [Errno 1] Operation not permitted: './output/20241104-165051-interfuser_baseline-224-interfuser_baseline/last.pth.tar' -> './output/20241104-165051-interfuser_baseline-224-interfuser_baseline/checkpoint-0.pth.tar' 请问有什么建议么？

我想我知道原因了。我将代码放在外接的固态硬盘中，就会导致上述问题，代码应该放在电脑内置的硬盘中。仅供参考
