### ISSUE TITLE
Train without Lidar

### ISSUE THREAD

**Issue by Mariusmarten** [opendilab/InterFuser#66]
When leaving out the ` --with-lidar` flag during training, I get the following error: 

`Traceback (most recent call last):
  File "train.py", line 1853, in <module>
    main()
  File "train.py", line 1236, in main
    train_metrics = train_one_epoch(
  File "train.py", line 1374, in train_one_epoch
    output = model(input)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/app/InterFuser/interfuser/timm/models/interfuser.py", line 987, in forward
    lidar = x["lidar"]
KeyError: 'lidar'`

Is there a specific flag for training without lidar? How can I reproduce the ablation results in the paper where training was done without Lidar?

**Comment by deepcs233** [comment]
Hi!

We haven't completed the related functions about this flag.  You may delete https://github.com/opendilab/InterFuser/blob/e4f0314482124bb06a475c3f6fb4bfe3a2701c4d/interfuser/timm/models/interfuser.py#L987 
and
https://github.com/opendilab/InterFuser/blob/e4f0314482124bb06a475c3f6fb4bfe3a2701c4d/interfuser/timm/models/interfuser.py#L1008
